# Generated by Django 6.0 on 2026-01-01 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vendor_remove_material_vendor_material_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('client_created', 'Client Created'), ('client_updated', 'Client Updated'), ('client_deleted', 'Client Deleted'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('payment_recorded', 'Payment Recorded'), ('material_created', 'Material Created'), ('material_updated', 'Material Updated'), ('material_deleted', 'Material Deleted'), ('reorder_created', 'Reorder Created'), ('invoice_created', 'Invoice Created')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('reorder_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
